---
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta4
kubernetesVersion: v1.32.3
proxy:
  disabled: true
apiServer:
  extraArgs:
    - name: profiling
      value: "false"
    - name: audit-policy-file
      value: /etc/kubernetes/audit-policy.yaml
    - name: audit-log-path
      value: /var/log/kubernetes/audit/audit.log
    - name: audit-log-maxage
      value: "30"
    - name: audit-log-maxbackup
      value: "10"
    - name: audit-log-maxsize
      value: "100"
    - name: encryption-provider-config
      value: /etc/kubernetes/enc/encryption-config.yaml
    - name: kubelet-certificate-authority
      value: /etc/kubernetes/pki/ca.crt
  extraVolumes:
    - name: audit
      hostPath: /etc/kubernetes/audit-policy.yaml
      mountPath: /etc/kubernetes/audit-policy.yaml
      readOnly: true
      pathType: File
    - name: audit-log
      hostPath: /var/log/kubernetes/audit/
      mountPath: /var/log/kubernetes/audit/
      readOnly: false
      pathType: DirectoryOrCreate
    - name: encryption-config
      hostPath: /etc/kubernetes/enc/encryption-config.yaml
      mountPath: /etc/kubernetes/enc/encryption-config.yaml
      readOnly: true
      pathType: File
controllerManager:
  extraArgs:
    - name: profiling
      value: "false"
scheduler:
  extraArgs:
    - name: profiling
      value: "false"
