---
name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  kubesec-sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Combine Kubernetes manifests into a single file
        run: |
          cat manifests/{allow-all-dns-ingress,allow-apiserver-ingress,cilium-health-checks,cilium-ingress,coredns-egress,gvisor-runtimeclass,hubble-relay-egress,intercept-all-dns-egress}.yaml > all-manifests.yaml
      - name: Run kubesec scanner
        uses: controlplaneio/kubesec-action@main
        with:
          input: all-manifests.yaml
          exit-code: "0"
          format: json
          output: kubesec-results.json
      - name: Print Kubesec SAST results
        run: cat kubesec-results.json
  opentofu-aws:
    runs-on: ubuntu-latest
    steps:
      - name: OpenTofu - Setup Tofu
        uses: opentofu/setup-opentofu@v1
      - name: Checkout
        uses: actions/checkout@v4
      - name: Initialize OpenTofu without backend
        run: |
          tofu -chdir="opentofu/aws/" init -backend=false
      - name: Check OpenTofu formatting
        run: |
          tofu -chdir="opentofu/aws/" fmt -recursive -check
      - name: Validate OpenTofu configuration
        run: |
          tofu -chdir="opentofu/aws/" validate
